use_frameworks!

platform :ios, '9.0'

target 'XMTest_Example' do
  pod 'XMLYTest', :path => '../'

  target 'XMTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
